Repository udistrital/arka_cliente, pull requests merged in 2021-04, with the labels that each got.

#594 Feat/configuracion
  src/app/@core/data/configuracion.service.ts
  src/app/@core/data/disponibilidad-movimientos.service.spec.ts
  src/app/@core/data/disponibilidad-movimientos.service.ts
  src/app/@core/data/menu.service.ts
  src/app/@core/data/models/aplicacion.ts
  src/app/@core/data/models/configuracion_crud.ts
  src/app/@core/data/models/menu_opcion.ts
  src/app/@core/data/models/menu_opcion_padre.ts
  src/app/@core/data/models/metodo_http.ts
  src/app/@core/data/models/notificacion.ts
  src/app/@core/data/models/notificacion_configuracion.ts
  src/app/@core/data/models/notificacion_configuracion_perfil.ts
  src/app/@core/data/models/notificacion_estado.ts
  src/app/@core/data/models/notificacion_estado_usuario.ts
  src/app/@core/data/models/notificacion_tipo.ts
  src/app/@core/data/models/parametro.ts
  src/app/@core/data/models/perfil.ts
  src/app/@core/data/models/perfil_x_menu_opcion.ts
  src/app/@core/data/users.service.ts
  src/app/@core/utils/notificaciones.service.ts
  src/app/helpers/entradas/entradaHelper.ts
  src/app/helpers/salidas/salidasHelper.ts
  src/app/managers/requestManager.ts
  src/app/pages/acta-recibido/capturar-elementos/capturar-elementos.component.html
  src/app/pages/acta-recibido/capturar-elementos/capturar-elementos.component.ts
  src/app/pages/acta-recibido/consulta-acta-recibido/consulta-acta-recibido.component.ts
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
  src/app/pages/acta-recibido/edicion-acta-recibido/reglas.ts
  src/app/pages/catalogo-bienes/crud-movimientos/crud-movimiento.component.ts
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.html
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
  src/app/pages/pages-menu.ts
  src/app/pages/pages.component.ts
  src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: desarrollo

#609 fix: interceptacion de entradas/salidas (faltó en #594)
  src/app/helpers/entradas/entradaHelper.ts
  src/app/helpers/salidas/salidasHelper.ts
Labels: bug

#612 Fix/permisos acta
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.html
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
Labels: Modulo de Acta de recibido, bug

#619 Feat/bloqueo movimientos bodega
  src/app/@core/utils/nuxeo.service.ts
  src/app/helpers/bodega_consumo/bodegaConsumoHelper.ts
  src/app/pages/bodega-consumo/agregar-elementos/agregar-elementos.component.html
  src/app/pages/bodega-consumo/agregar-elementos/agregar-elementos.component.ts
  src/app/pages/bodega-consumo/ajustar-cantidad/ajustar-cantidad.component.html
  src/app/pages/bodega-consumo/ajustar-cantidad/ajustar-cantidad.component.ts
  src/app/pages/bodega-consumo/apertura-kardex/apertura-kardex.component.html
  src/app/pages/bodega-consumo/apertura-kardex/apertura-kardex.component.ts
  src/app/pages/bodega-consumo/asignacion-kardex/asignacion-kardex.component.html
  src/app/pages/bodega-consumo/asignacion-kardex/asignacion-kardex.component.scss
  src/app/pages/bodega-consumo/asignacion-kardex/asignacion-kardex.component.ts
  src/app/pages/bodega-consumo/bodega-consumo-routing.module.ts
  src/app/pages/bodega-consumo/bodega-consumo.module.ts
  src/app/pages/bodega-consumo/bodega-sin-asignar/bodega-sin-asignar.component.html
  src/app/pages/bodega-consumo/bodega-sin-asignar/bodega-sin-asignar.component.ts
  src/app/pages/bodega-consumo/consulta-kardex/consulta-kardex.component.html
  src/app/pages/bodega-consumo/consulta-kardex/consulta-kardex.component.ts
  src/app/pages/bodega-consumo/consulta-solicitud/consulta-solicitud.component.html
  src/app/pages/bodega-consumo/consulta-solicitud/consulta-solicitud.component.ts
  src/app/pages/bodega-consumo/detalle-solicitud/detalle-solicitud.component.html
  src/app/pages/bodega-consumo/detalle-solicitud/detalle-solicitud.component.ts
  src/app/pages/bodega-consumo/entrada-kardex/entrada-kardex.component.html
  src/app/pages/bodega-consumo/entrada-kardex/entrada-kardex.component.ts
  src/app/pages/bodega-consumo/form-elementos-seleccionados/form-elementos-seleccionados.component.html
  src/app/pages/bodega-consumo/form-elementos-seleccionados/form-elementos-seleccionados.component.scss
  src/app/pages/bodega-consumo/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
  src/app/pages/bodega-consumo/kardex/kardex.component.html
  src/app/pages/bodega-consumo/kardex/kardex.component.scss
  src/app/pages/bodega-consumo/kardex/kardex.component.ts
  src/app/pages/bodega-consumo/relacion-catalogo/relacion-catalogo.component.html
  src/app/pages/bodega-consumo/relacion-catalogo/relacion-catalogo.component.ts
  src/app/pages/bodega-consumo/respuesta-solicitudes/respuesta-solicitudes.component.html
  src/app/pages/bodega-consumo/respuesta-solicitudes/respuesta-solicitudes.component.scss
  src/app/pages/bodega-consumo/respuesta-solicitudes/respuesta-solicitudes.component.spec.ts
  src/app/pages/bodega-consumo/respuesta-solicitudes/respuesta-solicitudes.component.ts
  src/app/pages/catalogo-bienes/arbol/arbol.component.html
  src/app/pages/catalogo-bienes/arbol/arbol.component.ts
  src/app/pages/catalogo-bienes/registro-catalogo/registro-catalogo.component.html
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.html
  src/app/pages/catalogo-bienes/registro-elementos/registro-elementos.component.html
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: bug, desarrollo

#623 Feature/avaluos inmuebles
  src/app/@core/data/menu.service.ts
  src/app/pages/bienes-inmuebles/avaluo/avaluo.component.html
  src/app/pages/bienes-inmuebles/avaluo/avaluo.component.scss
  src/app/pages/bienes-inmuebles/avaluo/avaluo.component.spec.ts
  src/app/pages/bienes-inmuebles/avaluo/avaluo.component.ts
  src/app/pages/bienes-inmuebles/bienes-inmuebles-routing.module.ts
  src/app/pages/bienes-inmuebles/bienes-inmuebles.component.spec.ts
  src/app/pages/bienes-inmuebles/bienes-inmuebles.component.ts
  src/app/pages/bienes-inmuebles/bienes-inmuebles.module.ts
  src/app/pages/bienes-inmuebles/lista-bienes/lista-bienes.component.html
  src/app/pages/bienes-inmuebles/lista-bienes/lista-bienes.component.scss
  src/app/pages/bienes-inmuebles/lista-bienes/lista-bienes.component.spec.ts
  src/app/pages/bienes-inmuebles/lista-bienes/lista-bienes.component.ts
  src/app/pages/bienes-inmuebles/registro-inmuebles/registro-inmuebles.component.html
  src/app/pages/bienes-inmuebles/registro-inmuebles/registro-inmuebles.component.scss
  src/app/pages/bienes-inmuebles/registro-inmuebles/registro-inmuebles.component.spec.ts
  src/app/pages/bienes-inmuebles/registro-inmuebles/registro-inmuebles.component.ts
  src/app/pages/pages-routing.module.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: desarrollo
