Repository udistrital/arka_cliente, pull requests merged in 2021-01, with the labels that each got.

#405 Feature/control errores plantilla
  src/app/pages/acta-recibido/capturar-elementos/capturar-elementos.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: desarrollo

#416 fix: #363 permisos revisor
  src/app/pages/acta-recibido/consulta-acta-recibido/consulta-acta-recibido.component.ts
Labels: bug

#418 Feature/modulo salidas
  src/app/@core/store/services/list.service.ts
  src/app/helpers/catalogo-elementos/catalogoElementosHelper.ts
  src/app/helpers/salidas/salidasHelper.ts
  src/app/pages/salidas/consulta-salidas/consulta-salidas.component.html
  src/app/pages/salidas/consulta-salidas/consulta-salidas.component.ts
  src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.html
  src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
  src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
  src/environments/environment.ts
Labels: Modulo de salidas, desarrollo

#423 fix: Arreglos varios en bodega de consumo
  src/app/pages/bodega-consumo/agregar-elementos/agregar-elementos.component.html
  src/app/pages/bodega-consumo/agregar-elementos/agregar-elementos.component.ts
  src/app/pages/bodega-consumo/bodega-sin-asignar/bodega-sin-asignar.component.html
  src/app/pages/bodega-consumo/bodega-sin-asignar/bodega-sin-asignar.component.ts
  src/app/pages/bodega-consumo/consulta-solicitud/consulta-solicitud.component.html
  src/app/pages/bodega-consumo/consulta-solicitud/consulta-solicitud.component.ts
  src/app/pages/bodega-consumo/form-elementos-seleccionados/form-elementos-seleccionados.component.html
Labels: bug

#430 Fix: Id quemado en commit 00ef1f8 Soluciona todo lo de bodega de consumo
  src/app/helpers/bodega_consumo/bodegaConsumoHelper.ts
Labels: bug

#440 fix: manejo de retorno "null" (ver msg commit -->)
  src/app/pages/acta-recibido/consulta-acta-recibido/consulta-acta-recibido.component.ts
Labels: Modulo de Acta de recibido, bug

#443 Fix/salidas vacias
  src/app/pages/salidas/consulta-salidas/consulta-salidas.component.ts
Labels: bug

#444 feature: Correcciones tabla verificado
  src/app/pages/acta-recibido/verificacion-elementos/verificacion-elementos.component.ts
Labels: desarrollo

#447 Fix/vista salida
  src/app/pages/salidas/consulta-salidas/consulta-salidas.component.ts
Labels: bug

#438 Feature/entrada caja menor
  src/app/pages/entradas/caja-menor/caja-menor.component.html
  src/app/pages/entradas/caja-menor/caja-menor.component.scss
  src/app/pages/entradas/caja-menor/caja-menor.component.spec.ts
  src/app/pages/entradas/caja-menor/caja-menor.component.ts
  src/app/pages/entradas/entradas.module.ts
  src/app/pages/entradas/registro/registro.component.html
Labels: desarrollo

#461 Fix/l10n entradas
  src/app/pages/acta-recibido/acta-especial/acta-especial.component.ts
  src/app/pages/acta-recibido/consulta-acta-recibido/consulta-acta-recibido.component.html
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
  src/app/pages/acta-recibido/verificacion-acta-recibido/verificacion-acta-recibido.component.ts
  src/app/pages/entradas/adquisicion/adquisicion.component.html
  src/app/pages/entradas/caja-menor/caja-menor.component.html
  src/app/pages/entradas/consulta-entrada/consulta-entrada.component.html
  src/app/pages/entradas/consulta-entrada/consulta-entrada.component.ts
  src/app/pages/entradas/donacion/donacion.component.html
  src/app/pages/entradas/elaboracion-propia/elaboracion-propia.component.html
  src/app/pages/entradas/registro/registro.component.html
  src/app/pages/entradas/registro/registro.component.ts
  src/app/pages/entradas/reposicion/reposicion.component.html
  src/app/pages/entradas/sobrante/sobrante.component.html
  src/app/pages/entradas/terceros/terceros.component.html
  src/app/pages/salidas/tabla-entrada-aprobada/tabla-entrada-aprobada.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: Modulo de Acta de recibido, Modulo de entradas

#464 fix: build (propiedades ocultas/inexistentes)
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.html
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
Labels: bug

#468 Fix/boton guardar acta
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
Labels: bug

#471 Feature/entrada adiciones mejoras
  src/app/pages/entradas/adiciones-mejoras/adiciones-mejoras.component.html
  src/app/pages/entradas/adiciones-mejoras/adiciones-mejoras.component.scss
  src/app/pages/entradas/adiciones-mejoras/adiciones-mejoras.component.spec.ts
  src/app/pages/entradas/adiciones-mejoras/adiciones-mejoras.component.ts
  src/app/pages/entradas/caja-menor/caja-menor.component.ts
  src/app/pages/entradas/entradas.module.ts
  src/app/pages/entradas/intangibles-adquiridos/intangibles-adquiridos.component.html
  src/app/pages/entradas/intangibles-adquiridos/intangibles-adquiridos.component.scss
  src/app/pages/entradas/intangibles-adquiridos/intangibles-adquiridos.component.spec.ts
  src/app/pages/entradas/intangibles-adquiridos/intangibles-adquiridos.component.ts
  src/app/pages/entradas/registro/registro.component.html
  src/app/pages/entradas/registro/registro.component.ts
  src/app/pages/entradas/tabla-entradas/tabla-entradas.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: desarrollo

#474 Avance correcciones analista
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
  src/app/pages/catalogo-bienes/arbol/arbol.component.ts
  src/app/pages/catalogo-bienes/catalogo-bienes.module.ts
  src/app/pages/catalogo-bienes/consulta-catalogo/consulta-catalogo.component.html
  src/app/pages/catalogo-bienes/consulta-catalogo/consulta-catalogo.component.ts
  src/app/pages/catalogo-bienes/crud-grupo/crud-grupo.component.html
  src/app/pages/catalogo-bienes/crud-grupo/crud-grupo.component.ts
  src/app/pages/catalogo-bienes/crud-movimientos/crud-movimiento.component.html
  src/app/pages/catalogo-bienes/crud-movimientos/crud-movimiento.component.ts
  src/app/pages/catalogo-bienes/crud-subgrupo/crud-subgrupo.component.html
  src/app/pages/catalogo-bienes/crud-subgrupo/crud-subgrupo.component.ts
  src/app/pages/catalogo-bienes/inactivar-grupo/inactivar-grupo.component.html
  src/app/pages/catalogo-bienes/inactivar-grupo/inactivar-grupo.component.ts
  src/app/pages/catalogo-bienes/registro-catalogo/registro-catalogo.component.html
  src/app/pages/catalogo-bienes/registro-catalogo/registro-catalogo.component.ts
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.html
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
  src/app/pages/catalogo-bienes/registro-elementos/registro-elementos.component.html
  src/app/pages/catalogo-bienes/registro-elementos/registro-elementos.component.ts
  src/app/pages/catalogo/crud-catalogo/crud-catalogo.component.html
  src/app/pages/catalogo/crud-catalogo/crud-catalogo.component.ts
  src/app/pages/catalogo/list-catalogo/list-catalogo.component.html
  src/app/pages/catalogo/list-catalogo/list-catalogo.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: Modulo catalogo de bienes, Modulo de Acta de recibido, bug

#479 Fix/casilla activo catalogo
  src/app/@theme/components/dinamicform/dinamicform.component.html
  src/app/@theme/components/dinamicform/dinamicform.component.ts
  src/app/pages/catalogo/crud-catalogo/crud-catalogo.component.ts
  src/app/pages/catalogo/crud-catalogo/form-catalogo.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: Modulo catalogo de bienes
