Repository udistrital/arka_cliente, pull requests merged in 2021-07, with the labels that each got.

#663 Fix: Solución a bug en carga de actas
  src/app/@core/data/users.service.ts
  src/app/pages/acta-recibido/consulta-acta-recibido/consulta-acta-recibido.component.ts
Labels: bug

#674 Fix/i18n fixes
  src/app/pages/bodega-consumo/consulta-kardex/consulta-kardex.component.html
  src/app/pages/bodega-consumo/consulta-kardex/consulta-kardex.component.ts
  src/app/pages/catalogo-bienes/crud-movimientos/crud-movimiento.component.ts
  src/app/pages/catalogo/list-catalogo/list-catalogo.component.ts
  src/app/pages/salidas/consulta-salidas/consulta-salidas.component.html
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: bug, desarrollo

#676 Fix/proveedores acta
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
Labels: bug

#682 Fix: Solución a carga de contratistas
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
Labels: bug

#690 Fix: Solución error de cargas en edición de acta
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
Labels: Modulo de Acta de recibido, bug

#704 feature: Error Sede Dependencia
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
Labels: bug, desarrollo

#718 Feature/soporteerr2
  src/app/@core/data/documento.service.ts
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: desarrollo

#666 feature: forzar cuentas debito entradas iguales y credito salida igua…
  src/app/@core/data/models/catalogo/cuentas_grupo.ts
  src/app/helpers/catalogo-elementos/catalogoElementosHelper.ts
  src/app/pages/catalogo-bienes/crud-movimientos/crud-movimiento.component.ts
  src/app/pages/catalogo-bienes/registro-catalogo/registro-catalogo.component.ts
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.html
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
Labels: Modulo catalogo de bienes, Módulo Gestión Contable, desarrollo

#723 feature:Solución error en envió de correos #698
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
Labels: desarrollo
