Repository udistrital/arka_cliente, pull requests merged in 2021-03, with the labels that each got.

#541 Feat/contratistas de terceros
  src/app/@core/data/models/terceros.ts
  src/app/@core/data/models/terceros_criterio.ts
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.html
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.html
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
Labels: Modulo de Acta de recibido, desarrollo

#543 Arreglo bug consecutivos entradas
  src/app/pages/entradas/adquisicion/adquisicion.component.ts
  src/app/pages/entradas/aprovechamientos/aprovechamientos.component.ts
  src/app/pages/entradas/caja-menor/caja-menor.component.ts
  src/app/pages/entradas/donacion/donacion.component.ts
  src/app/pages/entradas/elaboracion-propia/elaboracion-propia.component.ts
  src/app/pages/entradas/extranjero/extranjero.component.ts
  src/app/pages/entradas/intangibles-adquiridos/intangibles-adquiridos.component.ts
  src/app/pages/entradas/intangibles-desarrollados/intangibles-desarrollados.component.ts
  src/app/pages/entradas/provisional/provisional.component.ts
  src/app/pages/entradas/reposicion/reposicion.component.ts
  src/app/pages/entradas/sobrante/sobrante.component.ts
Labels: Modulo de entradas, bug

#544 feat: Arreglo de devolutivos
  src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
Labels: desarrollo

#561 Feat/repo
  src/app/pages/entradas/consulta-entrada/consulta-entrada.component.html
  src/app/pages/entradas/consulta-entrada/consulta-entrada.component.ts
  src/app/pages/entradas/registro/registro.component.ts
  src/app/pages/entradas/reposicion/reposicion.component.html
  src/app/pages/entradas/reposicion/reposicion.component.ts
  src/app/pages/salidas/tabla-entrada-aprobada/tabla-entrada-aprobada.component.html
  src/app/pages/salidas/tabla-entrada-aprobada/tabla-entrada-aprobada.component.ts
Labels: desarrollo

#562 Feat/proveedores de terceros
  src/app/@core/data/models/terceros_criterio.ts
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.html
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.html
  src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
  src/app/pages/acta-recibido/ver-detalle/ver-detalle.component.html
  src/app/pages/acta-recibido/ver-detalle/ver-detalle.component.ts
  src/app/pages/acta-recibido/verificacion-acta-recibido/verificacion-acta-recibido.component.html
  src/app/pages/acta-recibido/verificacion-acta-recibido/verificacion-acta-recibido.component.ts
Labels: Modulo de Acta de recibido, desarrollo

#563 Feat/restringir asignacion cuentas
  src/app/@core/data/models/roles/rol_usuario.ts
  src/app/pages/catalogo-bienes/crud-movimientos/crud-movimiento.component.ts
  src/app/pages/catalogo-bienes/crud-movimientos/form-movimiento.ts
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.html
  src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
  src/app/pages/pages-menu.ts
  src/app/pages/pages.component.ts
Labels: Modulo catalogo de bienes, Módulo Gestión Contable, desarrollo

#573 Fix/doc proveedor tercero
  src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
  src/app/pages/entradas/reposicion/reposicion.component.ts
Labels: bug

#574 feat: Ajuste del formulario y arreglo de bug con el registro de la ob…
  src/app/pages/entradas/aprovechamientos/aprovechamientos.component.ts
  src/app/pages/entradas/reposicion/reposicion.component.html
  src/app/pages/entradas/reposicion/reposicion.component.ts
Labels: bug, desarrollo

#578 Feat/consulta entrada
  src/app/pages/entradas/consulta-entrada/consulta-entrada.component.ts
  src/app/pages/salidas/tabla-entrada-aprobada/tabla-entrada-aprobada.component.ts
Labels: desarrollo

#586 Fix Permitir volver a cargar los elementos al acta despues de que fue…
  src/app/pages/acta-recibido/capturar-elementos/capturar-elementos.component.ts
Labels: bug
